# Generated by Django 4.1.7 on 2023-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0002_course_featured_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.TextField(null=True),
        ),
    ]
