# Generated by Django 4.1.7 on 2023-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('interested_categories', models.TextField()),
            ],
        ),
    ]
