# Generated by Django 4.1.7 on 2023-03-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0004_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3.Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2.Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4.Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1.Teachers'},
        ),
    ]
