# Generated by Django 4.1.7 on 2023-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0005_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='skills',
        ),
    ]
