# Generated by Django 4.1.7 on 2023-03-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0006_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
